embeddings {
  tensor_name: "Dental SimCSE embeddings"
  metadata_path: "data/test/test2_labels.tsv"
  tensor_path: "data/model_simcse_data_dental_vectors.tsv"
}
embeddings {
  tensor_name: "TEST Dental SimCSE embeddings"
  metadata_path: "data/test/test2_labels.tsv"
  tensor_path: "data/model_simcse_data_dental_vectors.tsv"
}
